-- Create tables for AutoVed admin data

-- Hero slides table
CREATE TABLE IF NOT EXISTS hero_slides (
  id VARCHAR(255) PRIMARY KEY,
  background_image TEXT NOT NULL,
  car_name VARCHAR(255) NOT NULL,
  car_specs VARCHAR(255) NOT NULL,
  car_year VARCHAR(255) NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Hero settings table
CREATE TABLE IF NOT EXISTS hero_settings (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Promo settings table
CREATE TABLE IF NOT EXISTS promo_settings (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Video reviews table
CREATE TABLE IF NOT EXISTS video_reviews (
  id VARCHAR(255) PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  car_model VARCHAR(255) NOT NULL,
  cover_image TEXT NOT NULL,
  vk_embed_url TEXT NOT NULL,
  action VARCHAR(255) DEFAULT 'Смотреть',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- FAQ table
CREATE TABLE IF NOT EXISTS faq_items (
  id VARCHAR(255) PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Car cards table
CREATE TABLE IF NOT EXISTS car_cards (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  engine VARCHAR(255) NOT NULL,
  drive VARCHAR(50) NOT NULL,
  modification VARCHAR(255) NOT NULL,
  distance VARCHAR(255) NOT NULL,
  image_url TEXT NOT NULL,
  external_link TEXT NOT NULL,
  price VARCHAR(255) NOT NULL,
  year VARCHAR(255) NOT NULL,
  location VARCHAR(10) NOT NULL,
  is_new BOOLEAN DEFAULT FALSE,
  date VARCHAR(255) NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Cars settings table
CREATE TABLE IF NOT EXISTS cars_settings (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);