version: '3.8'

services:
  autoved-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - autoved-network

  mysql:
    image: mysql:8.0
    container_name: autoved_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/lib/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autoved-network

volumes:
  mysql_data:

networks:
  autoved-network:
    driver: bridge
