version: '3.8'

services:
  autoved-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Database Configuration
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # S3 Storage Configuration
      - S3_ENDPOINT=${S3_ENDPOINT:-https://s3.twcstorage.ru}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION:-ru-1}
    restart: unless-stopped
